### ISSUE TITLE
-info with unhandled exception

### ISSUE THREAD

**Issue by HappyMeCoder** [CaiB/GDStoSVG#2]
I tried your latest build, but got exception messages:

c:\Temp\GDS>GDStoSVG.exe topfile.gds -info
CSV file not specified or not found.
File version is 0x0005
Unhandled exception. System.IO.InvalidDataException: New property starting before previous one had value assigned.
   at GDStoSVG.GDSReader.ReadRecord(RecordType type, Byte[] data) in C:\projects\gdstosvg\GDStoSVG\GDSReader.cs:line 332
   at GDStoSVG.GDSReader.ReadFile(String fileName) in C:\projects\gdstosvg\GDStoSVG\GDSReader.cs:line 32
   at GDStoSVG.Program.Main(String[] args) in C:\projects\gdstosvg\GDStoSVG\Program.cs:line 58

**Comment by CaiB** [comment]
Hello, and thanks for giving my dumb project a try! 😅 
I see the problem, I misinterpreted the GDS format specification for the `PROPATTR`/`PROPVALUE` elements. I'll work on fixing it and get a new build out tonight for you to test.

**Comment by CaiB** [comment]
Oh, that problem was much simpler than expected. Give the [newest build 0.2.0.15](https://github.com/CaiB/GDStoSVG/releases/tag/auto-v0.2.0.15) a try and let me know how it goes.

**Comment by HappyMeCoder** [comment]
I have no further exception messages. Now i need to figure out how it works with the CSV file. At the moment i got a SVG with no content.

**Comment by CaiB** [comment]
OK, that's progress. However, there should definitely be something in there.

Does the program show you a list of detected layers?

If you open the SVG in a text editor, do you see shapes defined in there?

Perhaps you could also try specifying `-unit <name>` where `<name>` is one of the things that the program lists when you use `-info`, maybe it's just outputting the wrong item from the GDS file.

**Comment by CaiB** [comment]
Have you been able to make any progress on this? Please let me know if I can help out.

**Comment by CaiB** [comment]
Closing due to inactivity. Please feel free to re-open if you need any further help.
